export const supportedDocumentTypes = [
  "resume",
  "tender",
  "contract",
  "requirements",
] as const;

export type DocumentType = (typeof supportedDocumentTypes)[number];

// PRODUCT OWNER SAFE TO EDIT:
// These signals are used for document classification. Keep resume-heavy terms specific and avoid broad generic words.
export const resumeStructureSignals = {
  hard: [
    "קורות חיים",
    "curriculum vitae",
    "cv",
    "name:",
    "email:",
    "phone:",
    "טלפון",
    "מייל",
    "אימייל",
    "כתובת",
    "מספר זהות",
    "גיל",
    "linkedin",
  ],
  medium: [
    "ניסיון תעסוקתי",
    "ניסיון מקצועי",
    "ניסיון",
    "תעסוקתי",
    "השכלה",
    "מיומנויות",
    "כישורים",
    "שפות",
    "שירות צבאי",
    "פרויקטים",
    "פרויקט",
    "תפקיד",
    "חברה",
    "לימודים",
    "תואר",
    "אוניברסיטה",
    "מכללה",
    "פרופיל",
    "תמצית",
  ],
  weak: [
    "skills",
    "experience",
    "education",
    "work",
    "role",
    "manager",
    "team",
    "responsibilities",
    "employer",
    "position",
    "פרויקט",
    "ניהול",
    "תפקיד",
    "ארגון",
  ],
};

export const keywordMap: Record<DocumentType, string[]> = {
  resume: [
    "cv",
    "resume",
    "curriculum vitae",
    "קורות חיים",
  ],
  tender: [
    "request for proposal",
    "rfx",
    "tender",
    "bid",
    "procurement",
    "scope of work",
    "submission deadline",
    "proposal",
    "מכרז",
    "הצעה",
    "הזמנה",
  ],
  contract: [
    "agreement",
    "party",
    "hereinafter",
    "terms and conditions",
    "effective date",
    "obligation",
    "termination",
    "contract",
    "הסכם",
    "צדדים",
    "תנאים",
    "פיצוי",
    "התחייבות",
    "אחריות",
    "קנס",
    "תוקף",
    "רישום",
  ],
  requirements: [
    "requirements",
    "specifications",
    "shall",
    "must",
    "acceptance criteria",
    "functional requirements",
    "non-functional requirements",
    "dependencies",
    "gaps",
    "דרישות",
    "מפרט",
    "קריטריונים",
    "אינטגרציה",
    "בדיקות",
    "תכונות",
    "ביצועים",
  ],
};
