import type { ProductDashboardConfig } from "../types/product";
import { slotDefinitions } from "./slotDefinitions";

// PRODUCT OWNER SAFE TO EDIT
export const documentDashboards: Record<string, ProductDashboardConfig> = {
  resume: {
    docType: "resume",
    displayName: "Resume",
    audience: "hr",
    maxVisibleSlots: 6,
    defaultTone: "professional and concise",
    decisionLabels: {
      ready: "מתאים להמשך בדיקה",
      review: "דורש בדיקה נוספת",
      verify: "התאמה חלשה",
      fallback: "לא מספיק מידע",
    },
    defaultDecisionReasons: {
      ready: "המסמך מציג פרופיל מקצועי ברור וללא חסרים משמעותיים.",
      review: "יש פרטיים חשובים שלא הוסברו או חסרים קישורים להישגים.",
      verify: "יש צורך לאמת את הפרטים או הבהרת המשך מסלול.",
      fallback: "לא ניתן לזהות את המסמך כקורות חיים באופן אמין.",
    },
    slots: [
      slotDefinitions.candidate_snapshot,
      slotDefinitions.relevant_experience,
      slotDefinitions.skills_analysis,
      slotDefinitions.gaps_or_missing_info,
      slotDefinitions.interview_questions,
      slotDefinitions.next_step_recommendation,
      slotDefinitions.professional_profile,
      slotDefinitions.military_service,
      slotDefinitions.languages,
      slotDefinitions.key_projects,
      slotDefinitions.achievements,
      slotDefinitions.education,
      slotDefinitions.certifications,
    ],
  },
  contract: {
    docType: "contract",
    displayName: "Contract",
    audience: "business",
    maxVisibleSlots: 5,
    defaultTone: "risk-aware and precise",
    decisionLabels: {
      ready: "Proceed with contract",
      review: "Review contract terms",
      verify: "Verify contract conditions",
      fallback: "Unclear contract type",
    },
    defaultDecisionReasons: {
      ready: "The contract includes clear obligations and manageable risks.",
      review: "Some clauses require closer review before approval.",
      verify: "There are compliance or liability items that need confirmation.",
      fallback: "The document was not clearly identified as a contract.",
    },
    slots: [
      slotDefinitions.obligations,
      slotDefinitions.liabilities,
      slotDefinitions.risky_clauses,
      slotDefinitions.missing_protections,
      slotDefinitions.compliance_gaps,
    ],
  },
  tender: {
    docType: "tender",
    displayName: "Tender / RFP",
    audience: "bidder",
    maxVisibleSlots: 5,
    defaultTone: "evaluation-focused and clear",
    decisionLabels: {
      ready: "Bid-ready",
      review: "Review before bidding",
      verify: "Verify tender details",
      fallback: "Unclear tender type",
    },
    defaultDecisionReasons: {
      ready: "The tender defines requirements and timelines clearly.",
      review: "Some bid risks or dependencies should be confirmed.",
      verify: "Key documents or deadlines need verification.",
      fallback: "The document was not clearly identified as a tender.",
    },
    slots: [
      slotDefinitions.requirements_overview,
      slotDefinitions.deadlines,
      slotDefinitions.missing_documents,
      slotDefinitions.feasibility,
      slotDefinitions.bid_risks,
    ],
  },
  requirements: {
    docType: "requirements",
    displayName: "Requirements / Specifications",
    audience: "analyst",
    maxVisibleSlots: 5,
    defaultTone: "analytical and structured",
    decisionLabels: {
      ready: "Requirements are actionable",
      review: "Review requirements",
      verify: "Verify requirements completeness",
      fallback: "Unclear requirements type",
    },
    defaultDecisionReasons: {
      ready: "The requirements are clear and mostly complete.",
      review: "Missing details or contradictions should be addressed.",
      verify: "Dependencies or acceptance criteria need confirmation.",
      fallback: "The document was not clearly identified as requirements.",
    },
    slots: [
      slotDefinitions.clarity,
      slotDefinitions.completeness,
      slotDefinitions.contradictions,
      slotDefinitions.dependencies,
      slotDefinitions.missing_details,
    ],
  },
  generic: {
    docType: "generic",
    displayName: "General Document",
    audience: "generic",
    maxVisibleSlots: 5,
    defaultTone: "neutral and factual",
    decisionLabels: {
      ready: "Ready for review",
      review: "Review document",
      verify: "Verify document content",
      fallback: "Unclear document type",
    },
    defaultDecisionReasons: {
      ready: "The document contains a clear, structured narrative.",
      review: "Additional context would improve decision making.",
      verify: "Important details may be missing or ambiguous.",
      fallback: "The document type could not be reliably identified.",
    },
    slots: [
      slotDefinitions.summary_slot,
      slotDefinitions.key_points,
      slotDefinitions.risks,
      slotDefinitions.missing_info,
      slotDefinitions.actions,
    ],
  },
};
