import type { ProductSlotConfig } from "../types/product";

export const slotDefinitions: Record<string, ProductSlotConfig> = {
  // PRODUCT OWNER SAFE TO EDIT: resume-targeted slot titles and helper text.
  candidate_snapshot: {
    type: "candidate_snapshot",
    title: "Candidate Snapshot",
    helperText: "Who the candidate appears to be based on the resume.",
    priority: 10,
    visibility: "required",
  },
  professional_profile: {
    type: "professional_profile",
    title: "Professional Profile",
    helperText: "The candidate's business, technical, or management orientation.",
    priority: 2,
    visibility: "optional",
  },
  relevant_experience: {
    type: "relevant_experience",
    title: "Relevant Experience",
    helperText: "Actual roles, job periods, or highlights from the resume.",
    priority: 9,
    visibility: "required",
  },
  skills_analysis: {
    type: "skills_analysis",
    title: "Skills Analysis",
    helperText: "Grouped technical, business, tool, and soft skills from the resume.",
    priority: 8,
    visibility: "recommended",
  },
  military_service: {
    type: "military_service",
    title: "Military Service",
    helperText: "Summary of military or national service when present.",
    priority: 3,
    visibility: "optional",
  },
  languages: {
    type: "languages",
    title: "Languages",
    helperText: "Languages and proficiency levels listed in the resume.",
    priority: 3,
    visibility: "optional",
  },
  key_projects: {
    type: "key_projects",
    title: "Key Projects",
    helperText: "Explicit projects described in the resume.",
    priority: 3,
    visibility: "optional",
  },
  achievements: {
    type: "achievements",
    title: "Achievements",
    helperText: "Explicit achievements, impact, or results.",
    priority: 3,
    visibility: "optional",
  },
  education: {
    type: "education",
    title: "Education",
    helperText: "Education background and academic track details.",
    priority: 3,
    visibility: "optional",
  },
  certifications: {
    type: "certifications",
    title: "Certifications",
    helperText: "Professional certifications, courses, or formal training credentials.",
    priority: 3,
    visibility: "optional",
  },
  gaps_or_missing_info: {
    type: "gaps_or_missing_info",
    title: "Gaps or Missing Information",
    helperText: "Information that is unclear or missing in the resume.",
    priority: 7,
    visibility: "required",
  },
  interview_questions: {
    type: "interview_questions",
    title: "Interview Questions",
    helperText: "Questions based only on resume content.",
    priority: 6,
    visibility: "optional",
  },
  next_step_recommendation: {
    type: "next_step_recommendation",
    title: "Next Step Recommendation",
    helperText: "A generic hiring-screening next step.",
    priority: 5,
    visibility: "optional",
  },
  obligations: {
    type: "obligations",
    title: "Key Obligations",
    helperText: "Essential commitments and deliverables in the document.",
    priority: 5,
    visibility: "required",
  },
  liabilities: {
    type: "liabilities",
    title: "Liabilities & Exposure",
    helperText: "Exposure or responsibility that should be reviewed.",
    priority: 5,
    visibility: "recommended",
  },
  risky_clauses: {
    type: "risky_clauses",
    title: "Risky Clauses",
    helperText: "Clauses that may create legal, financial, or operational risk.",
    priority: 5,
    visibility: "required",
  },
  missing_protections: {
    type: "missing_protections",
    title: "Missing Protections",
    helperText: "Protective language or clauses that are absent.",
    priority: 4,
    visibility: "recommended",
  },
  compliance_gaps: {
    type: "compliance_gaps",
    title: "Compliance Gaps",
    helperText: "Requirements or controls that are missing from the document.",
    priority: 4,
    visibility: "recommended",
  },
  requirements_overview: {
    type: "requirements_overview",
    title: "Requirements Overview",
    helperText: "The core functional and non-functional requirements found.",
    priority: 5,
    visibility: "required",
  },
  deadlines: {
    type: "deadlines",
    title: "Deadlines & Timelines",
    helperText: "Critical timeline items that affect delivery or response.",
    priority: 5,
    visibility: "recommended",
  },
  missing_documents: {
    type: "missing_documents",
    title: "Missing Documents",
    helperText: "Required attachments or submittals that are absent.",
    priority: 4,
    visibility: "recommended",
  },
  feasibility: {
    type: "feasibility",
    title: "Feasibility Assessment",
    helperText: "Whether the proposal or scope is realistic and actionable.",
    priority: 4,
    visibility: "recommended",
  },
  bid_risks: {
    type: "bid_risks",
    title: "Bid Risks",
    helperText: "Risks that may affect a competitive response or award.",
    priority: 4,
    visibility: "recommended",
  },
  clarity: {
    type: "clarity",
    title: "Clarity",
    helperText: "How clearly the document communicates its requirements.",
    priority: 5,
    visibility: "required",
  },
  completeness: {
    type: "completeness",
    title: "Completeness",
    helperText: "How complete the stated requirements are.",
    priority: 5,
    visibility: "required",
  },
  contradictions: {
    type: "contradictions",
    title: "Contradictions",
    helperText: "Conflicting or inconsistent requirements in the document.",
    priority: 4,
    visibility: "recommended",
  },
  dependencies: {
    type: "dependencies",
    title: "Dependencies",
    helperText: "External or internal dependencies that affect success.",
    priority: 4,
    visibility: "recommended",
  },
  missing_details: {
    type: "missing_details",
    title: "Missing Details",
    helperText: "Important details that are absent or underspecified.",
    priority: 4,
    visibility: "required",
  },
  summary_slot: {
    type: "summary_slot",
    title: "Summary",
    helperText: "A concise, decision-ready summary of the document.",
    priority: 5,
    visibility: "recommended",
  },
  key_points: {
    type: "key_points",
    title: "Key Points",
    helperText: "The most important items decision makers need to know.",
    priority: 4,
    visibility: "recommended",
  },
  actions: {
    type: "actions",
    title: "Recommended Actions",
    helperText: "Suggested next steps based on the document review.",
    priority: 3,
    visibility: "optional",
  },
  risks: {
    type: "risks",
    title: "Risks",
    helperText: "Top risks identified in the document.",
    priority: 5,
    visibility: "required",
  },
  missing_info: {
    type: "missing_info",
    title: "Missing Information",
    helperText: "Critical information missing from the document.",
    priority: 5,
    visibility: "required",
  },
};
